import Enumerable from './Enumerable';
import { IterableType } from './utils';

/**
 * Enumerable of groups, generated by the groupBy methods
 * @internal
 * @template T
 * @template TKey
 */
export default class GroupEnumerable<T, TKey> extends Enumerable<T> {
  key: TKey;
  constructor(iterable: IterableType<T>, key: TKey) {
    super(iterable);
    this.key = key;
  }
}
